name: "Docs Build"

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/docs.yml'
      - '.github/scripts/generate-docs.sh'
      - '**/*.swift'

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

jobs:
  BuildWebsite:
    name: "Build Docs"
    runs-on: macos-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      
      - name: 👷 Build Website
        run: .github/scripts/generate-docs.sh
