name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - '.github/workflows/ios-tests.yml'
              - '**/*.swift'

  build-ios-matrix:
    name: iOS Metrix
    if: ${{ github.event_name == 'push' || needs.check-changes.outputs.changed == 'true' }}
    needs: check-changes
    strategy:
      matrix:
        xcode: [ "15.4" ]
        os: [ macos-14 ]
    runs-on: ${{ matrix.os }}

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: xcrun xcodebuild test -workspace . -scheme "Vexil" -destination "platform=iOS Simulator,name=Any iOS Simulator Device"

  build-ios:
    runs-on: ubuntu-latest
    name: iOS Tests
    if: ${{ github.event_name == 'push' || needs.check-changes.outputs.changed == 'true' }}
    needs: build-ios-matrix
    steps:
      - name: Check build matrix status
        if: ${{ needs.build-ios-matrix.result == 'failure' }}
        run: exit 1
