name: SonarCloud

on:
  push:
    branches: [ main, code-coverage ]
    paths:
      - '.github/workflows/sonarcloud.yml'
      - 'sonar-project.properties'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/sonarcloud.yml'
      - 'sonar-project.properties'
      - '**/*.swift'

jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Test Coverage
        run: swift test --enable-test-discovery --enable-code-coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
