name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
    
jobs:
  test-macos:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test | .github/convert-errors-github-annotations.sh
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

  test-linux:
    name: Linux
    runs-on: ubuntu-latest

    container:
      image: swift:5.2

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery | .github/convert-errors-github-annotations.sh