name: tvOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - '.github/workflows/tvos-tests.yml'
              - '**/*.swift'

  build-tvos-matrix:
    name: tvOS Metrix
    if: ${{ github.event_name == 'push' || needs.check-changes.outputs.changed == 'true' }}
    needs: check-changes
    strategy:
      matrix:
        xcode: [ "15.4" ]
        os: [ macos-14 ]
    runs-on: ${{ matrix.os }}

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: xcrun xcodebuild test -workspace . -scheme "Vexil" -destination "platform=tvOS Simulator,name=Any tvOS Simulator Device"

  build-tvos:
    runs-on: ubuntu-latest
    name: tvOS Tests
    if: ${{ github.event_name == 'push' || needs.check-changes.outputs.changed == 'true' }}
    needs: build-tvos-matrix
    steps:
      - name: Check build matrix status
        if: ${{ needs.build-tvos-matrix.result == 'failure' }}
        run: exit 1
